repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Format code (black)
        language_version: python3.8
  - repo: local
    hooks:
      - id: pii-check
        exclude: (pii-check-hook.py | README.md)
        name: Check for PII
        description: this hook checks if modified files have PII and marks it.
        entry: pii_check --url https://api.private-ai.com/deid/v3/process_text --env-file-path /Users/ketakigokhale/Documents/package-git-integration/.env
        pass_filenames: false
        verbose: true
        language: python
