- id: pii-check
  name: Check for PII
  description: this hook checks if modified files have PII and marks it.
  entry: pii_check
  verbose: true
  require_serial: true
  language: python
  types: [file, text]